version: "2"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./gitea:/data
    restart: always
    networks:
      - default
    ports:
      - "${GITEA_SSH_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
